export type SupplierKey = 'textile' | 'chaussure' | 'maroquinerie';

export type CatalogVariant = {
  couleur?: string;
  taille?: string;
  quantity: number;
  minThreshold: number;
};

export type CatalogProduct = {
  name: string;
  sku: string;
  category: string;
  purchasePrice: number;
  sellingPrice: number;
  tax: number;
  description: string;
  supplier: SupplierKey;
  variants?: CatalogVariant[];
  quantity?: number;
  minThreshold?: number;
};

export const CLOTHING_CATEGORIES = [
  'Hauts',
  'Bas',
  'Robes & jupes',
  'Vestes',
  'Chaussures',
  'Chaussettes & lingerie',
  'Sacs & cartables',
  'Accessoires',
] as const;

const TVA = 19;

export const CLOTHING_CATALOG: CatalogProduct[] = [
  {
    name: 'T-shirt coton Essential',
    sku: 'TEE-ESS',
    category: 'Hauts',
    purchasePrice: 18,
    sellingPrice: 39.9,
    tax: TVA,
    description: 'T-shirt unisexe en coton peigné 180 g/m², coupe droite.',
    supplier: 'textile',
    variants: [
      { couleur: 'Noir', taille: 'S', quantity: 18, minThreshold: 4 },
      { couleur: 'Noir', taille: 'M', quantity: 28, minThreshold: 6 },
      { couleur: 'Noir', taille: 'L', quantity: 22, minThreshold: 5 },
      { couleur: 'Blanc', taille: 'S', quantity: 14, minThreshold: 4 },
      { couleur: 'Blanc', taille: 'M', quantity: 24, minThreshold: 6 },
      { couleur: 'Blanc', taille: 'L', quantity: 16, minThreshold: 4 },
      { couleur: 'Beige', taille: 'M', quantity: 12, minThreshold: 4 },
      { couleur: 'Beige', taille: 'L', quantity: 8, minThreshold: 3 },
    ],
  },
  {
    name: 'Polo piqué',
    sku: 'POL-PIQ',
    category: 'Hauts',
    purchasePrice: 22,
    sellingPrice: 54.9,
    tax: TVA,
    description: 'Polo piqué col boutonné, coupe semi-ajustée.',
    supplier: 'textile',
    variants: [
      { couleur: 'Marine', taille: 'M', quantity: 16, minThreshold: 4 },
      { couleur: 'Marine', taille: 'L', quantity: 14, minThreshold: 4 },
      { couleur: 'Blanc', taille: 'M', quantity: 12, minThreshold: 4 },
      { couleur: 'Blanc', taille: 'L', quantity: 10, minThreshold: 3 },
    ],
  },
  {
    name: 'Chemise oxford',
    sku: 'CHM-OXF',
    category: 'Hauts',
    purchasePrice: 29,
    sellingPrice: 69.9,
    tax: TVA,
    description: 'Chemise oxford manches longues, col italien.',
    supplier: 'textile',
    variants: [
      { couleur: 'Blanc', taille: 'M', quantity: 10, minThreshold: 3 },
      { couleur: 'Blanc', taille: 'L', quantity: 12, minThreshold: 3 },
      { couleur: 'Blanc', taille: 'XL', quantity: 8, minThreshold: 2 },
      { couleur: 'Ciel', taille: 'M', quantity: 9, minThreshold: 3 },
      { couleur: 'Ciel', taille: 'L', quantity: 11, minThreshold: 3 },
    ],
  },
  {
    name: 'Sweat à capuche',
    sku: 'SWT-CAP',
    category: 'Hauts',
    purchasePrice: 32,
    sellingPrice: 74.9,
    tax: TVA,
    description: 'Sweat molleton doux, capuche doublée, poche kangourou.',
    supplier: 'textile',
    variants: [
      { couleur: 'Gris', taille: 'M', quantity: 15, minThreshold: 4 },
      { couleur: 'Gris', taille: 'L', quantity: 18, minThreshold: 4 },
      { couleur: 'Noir', taille: 'M', quantity: 14, minThreshold: 4 },
      { couleur: 'Noir', taille: 'L', quantity: 16, minThreshold: 4 },
    ],
  },
  {
    name: 'Chemisier fluide',
    sku: 'CHS-FLU',
    category: 'Hauts',
    purchasePrice: 24,
    sellingPrice: 59.9,
    tax: TVA,
    description: 'Chemisier viscose fluide, coupe loose.',
    supplier: 'textile',
    variants: [
      { couleur: 'Blanc', taille: 'S', quantity: 9, minThreshold: 3 },
      { couleur: 'Blanc', taille: 'M', quantity: 11, minThreshold: 3 },
      { couleur: 'Rose', taille: 'S', quantity: 7, minThreshold: 3 },
      { couleur: 'Rose', taille: 'M', quantity: 8, minThreshold: 3 },
    ],
  },
  {
    name: 'Jean slim stretch',
    sku: 'JEA-SLM',
    category: 'Bas',
    purchasePrice: 48,
    sellingPrice: 99.9,
    tax: TVA,
    description: 'Jean slim stretch 5 poches, denim 11 oz.',
    supplier: 'textile',
    variants: [
      { couleur: 'Bleu', taille: '38', quantity: 8, minThreshold: 3 },
      { couleur: 'Bleu', taille: '40', quantity: 14, minThreshold: 4 },
      { couleur: 'Bleu', taille: '42', quantity: 10, minThreshold: 3 },
      { couleur: 'Noir', taille: '38', quantity: 0, minThreshold: 3 },
      { couleur: 'Noir', taille: '40', quantity: 9, minThreshold: 3 },
      { couleur: 'Noir', taille: '42', quantity: 7, minThreshold: 3 },
    ],
  },
  {
    name: 'Chino coupe droite',
    sku: 'CHI-DRT',
    category: 'Bas',
    purchasePrice: 34,
    sellingPrice: 79.9,
    tax: TVA,
    description: 'Pantalon chino coton, coupe droite.',
    supplier: 'textile',
    variants: [
      { couleur: 'Beige', taille: '40', quantity: 11, minThreshold: 3 },
      { couleur: 'Beige', taille: '42', quantity: 13, minThreshold: 3 },
      { couleur: 'Kaki', taille: '40', quantity: 8, minThreshold: 3 },
      { couleur: 'Kaki', taille: '42', quantity: 9, minThreshold: 3 },
    ],
  },
  {
    name: 'Jogging molleton',
    sku: 'JOG-MOL',
    category: 'Bas',
    purchasePrice: 21,
    sellingPrice: 49.9,
    tax: TVA,
    description: 'Jogging molleton, taille élastiquée, bas resserré.',
    supplier: 'textile',
    variants: [
      { couleur: 'Noir', taille: 'S', quantity: 10, minThreshold: 3 },
      { couleur: 'Noir', taille: 'M', quantity: 16, minThreshold: 4 },
      { couleur: 'Noir', taille: 'L', quantity: 14, minThreshold: 4 },
    ],
  },
  {
    name: 'Short chino',
    sku: 'SHO-CHI',
    category: 'Bas',
    purchasePrice: 18,
    sellingPrice: 44.9,
    tax: TVA,
    description: 'Short chino été, longueur genou.',
    supplier: 'textile',
    variants: [
      { couleur: 'Beige', taille: 'M', quantity: 12, minThreshold: 4 },
      { couleur: 'Beige', taille: 'L', quantity: 10, minThreshold: 3 },
    ],
  },
  {
    name: 'Robe midi lin',
    sku: 'ROB-LIN',
    category: 'Robes & jupes',
    purchasePrice: 38,
    sellingPrice: 85.9,
    tax: TVA,
    description: 'Robe midi en lin lavé, bretelles ajustables.',
    supplier: 'textile',
    variants: [
      { couleur: 'Olive', taille: 'S', quantity: 6, minThreshold: 2 },
      { couleur: 'Olive', taille: 'M', quantity: 8, minThreshold: 3 },
      { couleur: 'Sable', taille: 'S', quantity: 5, minThreshold: 2 },
      { couleur: 'Sable', taille: 'M', quantity: 7, minThreshold: 2 },
    ],
  },
  {
    name: 'Jupe plissée',
    sku: 'JUP-PLI',
    category: 'Robes & jupes',
    purchasePrice: 26,
    sellingPrice: 64.9,
    tax: TVA,
    description: 'Jupe midi plissée, taille élastique.',
    supplier: 'textile',
    variants: [
      { couleur: 'Noir', taille: 'S', quantity: 7, minThreshold: 3 },
      { couleur: 'Noir', taille: 'M', quantity: 9, minThreshold: 3 },
      { couleur: 'Noir', taille: 'L', quantity: 6, minThreshold: 2 },
    ],
  },
  {
    name: 'Veste bomber',
    sku: 'VES-BOM',
    category: 'Vestes',
    purchasePrice: 52,
    sellingPrice: 119.9,
    tax: TVA,
    description: 'Veste bomber légère, zip métal, poches plaquées.',
    supplier: 'textile',
    variants: [
      { couleur: 'Noir', taille: 'M', quantity: 8, minThreshold: 3 },
      { couleur: 'Noir', taille: 'L', quantity: 9, minThreshold: 3 },
    ],
  },
  {
    name: 'Cardigan maille',
    sku: 'CAR-MAI',
    category: 'Vestes',
    purchasePrice: 31,
    sellingPrice: 72.9,
    tax: TVA,
    description: 'Cardigan maille fine, boutons nacre.',
    supplier: 'textile',
    variants: [
      { couleur: 'Crème', taille: 'S', quantity: 6, minThreshold: 2 },
      { couleur: 'Crème', taille: 'M', quantity: 8, minThreshold: 3 },
    ],
  },
  {
    name: 'Baskets urbaines',
    sku: 'BAS-URB',
    category: 'Chaussures',
    purchasePrice: 55,
    sellingPrice: 129.9,
    tax: TVA,
    description: 'Baskets cuir synthétique, semelle crêpe.',
    supplier: 'chaussure',
    variants: [
      { couleur: 'Blanc', taille: '39', quantity: 6, minThreshold: 2 },
      { couleur: 'Blanc', taille: '40', quantity: 8, minThreshold: 3 },
      { couleur: 'Blanc', taille: '41', quantity: 7, minThreshold: 2 },
      { couleur: 'Blanc', taille: '42', quantity: 9, minThreshold: 3 },
      { couleur: 'Noir', taille: '40', quantity: 7, minThreshold: 2 },
      { couleur: 'Noir', taille: '41', quantity: 8, minThreshold: 3 },
      { couleur: 'Noir', taille: '42', quantity: 6, minThreshold: 2 },
    ],
  },
  {
    name: 'Sandales cuir',
    sku: 'SAN-CUI',
    category: 'Chaussures',
    purchasePrice: 28,
    sellingPrice: 69.9,
    tax: TVA,
    description: 'Sandales plates en cuir, bride réglable.',
    supplier: 'chaussure',
    variants: [
      { couleur: 'Camel', taille: '37', quantity: 5, minThreshold: 2 },
      { couleur: 'Camel', taille: '38', quantity: 7, minThreshold: 2 },
      { couleur: 'Camel', taille: '39', quantity: 6, minThreshold: 2 },
    ],
  },
  {
    name: 'Mocassins',
    sku: 'MOC-CLA',
    category: 'Chaussures',
    purchasePrice: 42,
    sellingPrice: 99.9,
    tax: TVA,
    description: 'Mocassins classiques, semelle cuir.',
    supplier: 'chaussure',
    variants: [
      { couleur: 'Marron', taille: '40', quantity: 5, minThreshold: 2 },
      { couleur: 'Marron', taille: '41', quantity: 6, minThreshold: 2 },
      { couleur: 'Marron', taille: '42', quantity: 5, minThreshold: 2 },
    ],
  },
  {
    name: 'Chaussettes coton — pack 3',
    sku: 'CHA-COT3',
    category: 'Chaussettes & lingerie',
    purchasePrice: 4.5,
    sellingPrice: 12.9,
    tax: TVA,
    description: 'Pack de 3 paires, coton peigné, mi-mollet.',
    supplier: 'textile',
    variants: [
      { couleur: 'Noir', quantity: 40, minThreshold: 10 },
      { couleur: 'Blanc', quantity: 32, minThreshold: 10 },
      { couleur: 'Gris', quantity: 22, minThreshold: 8 },
    ],
  },
  {
    name: 'Chaussettes invisibles — pack 5',
    sku: 'CHA-INV5',
    category: 'Chaussettes & lingerie',
    purchasePrice: 6,
    sellingPrice: 16.9,
    tax: TVA,
    description: 'Pack de 5 paires invisibles, talon silicone.',
    supplier: 'textile',
    variants: [{ couleur: 'Beige', quantity: 3, minThreshold: 8 }],
  },
  {
    name: 'Collants 20 deniers',
    sku: 'COL-20D',
    category: 'Chaussettes & lingerie',
    purchasePrice: 3.5,
    sellingPrice: 9.9,
    tax: TVA,
    description: 'Collants voile 20D, résille renforcée.',
    supplier: 'textile',
    variants: [
      { couleur: 'Noir', taille: 'S', quantity: 2, minThreshold: 6 },
      { couleur: 'Noir', taille: 'M', quantity: 8, minThreshold: 6 },
    ],
  },
  {
    name: 'Boxer coton pack 2',
    sku: 'BOX-COT2',
    category: 'Chaussettes & lingerie',
    purchasePrice: 8,
    sellingPrice: 24.9,
    tax: TVA,
    description: 'Pack de 2 boxers coton stretch.',
    supplier: 'textile',
    variants: [
      { couleur: 'Noir', taille: 'M', quantity: 18, minThreshold: 5 },
      { couleur: 'Noir', taille: 'L', quantity: 16, minThreshold: 5 },
    ],
  },
  {
    name: 'Cartable scolaire 2 compartiments',
    sku: 'CAR-SCO',
    category: 'Sacs & cartables',
    purchasePrice: 42,
    sellingPrice: 89.9,
    tax: TVA,
    description: 'Cartable dos renforcé, 2 compartiments, poche bouteille.',
    supplier: 'maroquinerie',
    variants: [
      { couleur: 'Marine', quantity: 14, minThreshold: 4 },
      { couleur: 'Bordeaux', quantity: 1, minThreshold: 4 },
    ],
  },
  {
    name: 'Sac à dos quotidien',
    sku: 'SAC-DOS',
    category: 'Sacs & cartables',
    purchasePrice: 28,
    sellingPrice: 64.9,
    tax: TVA,
    description: 'Sac à dos 18 L, compartiment laptop 14".',
    supplier: 'maroquinerie',
    variants: [
      { couleur: 'Noir', quantity: 16, minThreshold: 4 },
      { couleur: 'Kaki', quantity: 11, minThreshold: 3 },
    ],
  },
  {
    name: 'Sac cabas toile',
    sku: 'SAC-CAB',
    category: 'Sacs & cartables',
    purchasePrice: 12,
    sellingPrice: 34.9,
    tax: TVA,
    description: 'Cabas coton épais, anses longues.',
    supplier: 'maroquinerie',
    quantity: 22,
    minThreshold: 6,
  },
  {
    name: 'Trousse école',
    sku: 'TRU-ECO',
    category: 'Sacs & cartables',
    purchasePrice: 5,
    sellingPrice: 14.9,
    tax: TVA,
    description: 'Trousse zippée, doublure imprimée.',
    supplier: 'maroquinerie',
    variants: [{ couleur: 'Bleu', quantity: 30, minThreshold: 8 }],
  },
  {
    name: 'Sac bandoulière',
    sku: 'SAC-BAN',
    category: 'Sacs & cartables',
    purchasePrice: 24,
    sellingPrice: 59.9,
    tax: TVA,
    description: 'Sac bandoulière compact, rabat aimanté.',
    supplier: 'maroquinerie',
    variants: [{ couleur: 'Cognac', quantity: 9, minThreshold: 3 }],
  },
  {
    name: 'Ceinture cuir',
    sku: 'CEI-CUI',
    category: 'Accessoires',
    purchasePrice: 15,
    sellingPrice: 39.9,
    tax: TVA,
    description: 'Ceinture cuir pleine fleur, boucle argentée.',
    supplier: 'maroquinerie',
    variants: [
      { couleur: 'Noir', taille: '90', quantity: 10, minThreshold: 3 },
      { couleur: 'Noir', taille: '95', quantity: 8, minThreshold: 3 },
      { couleur: 'Marron', taille: '90', quantity: 7, minThreshold: 2 },
      { couleur: 'Marron', taille: '95', quantity: 6, minThreshold: 2 },
    ],
  },
  {
    name: 'Casquette baseball',
    sku: 'CAS-BAS',
    category: 'Accessoires',
    purchasePrice: 8,
    sellingPrice: 24.9,
    tax: TVA,
    description: 'Casquette coton, visière courbée, taille unique.',
    supplier: 'textile',
    variants: [{ couleur: 'Noir', quantity: 20, minThreshold: 5 }],
  },
  {
    name: 'Écharpe laine',
    sku: 'ECH-LAI',
    category: 'Accessoires',
    purchasePrice: 14,
    sellingPrice: 39.9,
    tax: TVA,
    description: 'Écharpe laine mélangée 180 × 40 cm.',
    supplier: 'textile',
    variants: [{ couleur: 'Camel', quantity: 11, minThreshold: 3 }],
  },
  {
    name: 'Bonnet côtes',
    sku: 'BON-COT',
    category: 'Accessoires',
    purchasePrice: 7,
    sellingPrice: 19.9,
    tax: TVA,
    description: 'Bonnet à côtes, maille stretch.',
    supplier: 'textile',
    variants: [{ couleur: 'Gris', quantity: 14, minThreshold: 4 }],
  },
  {
    name: 'Portefeuille cuir',
    sku: 'POR-CUI',
    category: 'Accessoires',
    purchasePrice: 16,
    sellingPrice: 44.9,
    tax: TVA,
    description: 'Portefeuille compact, 6 fentes cartes.',
    supplier: 'maroquinerie',
    variants: [{ couleur: 'Noir', quantity: 13, minThreshold: 3 }],
  },
];
